// This file is generated by Slice Machine. Update with care!

import RecommendedSubscriptionOption from './RecommendedSubscriptionOption';
import SubscriptionOption from './SubscriptionOption';

export {
	RecommendedSubscriptionOption,
	SubscriptionOption,
};

export const components = {
	recommended_subscription_option: RecommendedSubscriptionOption,
	subscription_option: SubscriptionOption,
};
